In [3]:
import pandas as pd
import requests
import numpy as nan
import math
import pprint

In [4]:
df= pd.read_csv('beer_association_scrape.csv')
df

,company_name,company_type,company_phone,street_address,city,state,zipcode,member_type,independent_craft
0,52 Brewing,Planning,no phone number,NaN,Dahlonega,GA,30533,Beer Association Associate Member,No Membership
1,6S Brewing Company,Taproom,(678) 597-8335,3111 Main Street,"Duluth,",GA,30096,Beer Association Member,Independent Craft Brewer
2,Abide Brewing Company,Micro,(678) 972-6747,110 Werz Industrial Blvd Ste 130,"Newnan,",GA,30263-5802,Beer Association Member,Independent Craft Brewer
3,Akademia Brewing Company,Brewpub,(706) 461-3208,150 Crane Dr,"Athens,",GA,30606-0600,No Seal,Independent Craft Brewer
4,Amici At Trillith,Brewpub,(678) 892-5858,355 Trilith Parkway STE 110,"Fayetteville,",GA,30214,No Seal,Independent Craft Brewer
...,...,...,...,...,...,...,...,...,...
169,Whistle Top Brew Company,Taproom,(706) 776-9556,248 N Main St,"Cornelia,",GA,30531,No Seal,Independent Craft Brewer
170,Wild Heaven - West End Brewery & Gardens,Brewpub,(404) 997-8589,1010 White St SW,"Atlanta,",GA,30310,Beer Association Member,Independent Craft Brewer
171,Wild Heaven Beer,Micro,(404) 997-8589,135B Maple St,"Decatur,",GA,30030-3953,Beer Association Member,Independent Craft Brewer
172,Wild Leap Brewing Company,Micro,(706) 298-6400,308 Main St,"Lagrange,",GA,30240-4504,Beer Association Member,Independent Craft Brewer
173,Yes Face Beer,Contract,(404) 213-3867,NaN,"Sun City Peachtree,",GA,NaN,No Membership,No Seal

In [5]:
df2 = df[df['street_address'].notna()]
df2

,company_name,company_type,company_phone,street_address,city,state,zipcode,member_type,independent_craft
1,6S Brewing Company,Taproom,(678) 597-8335,3111 Main Street,"Duluth,",GA,30096,Beer Association Member,Independent Craft Brewer
2,Abide Brewing Company,Micro,(678) 972-6747,110 Werz Industrial Blvd Ste 130,"Newnan,",GA,30263-5802,Beer Association Member,Independent Craft Brewer
3,Akademia Brewing Company,Brewpub,(706) 461-3208,150 Crane Dr,"Athens,",GA,30606-0600,No Seal,Independent Craft Brewer
4,Amici At Trillith,Brewpub,(678) 892-5858,355 Trilith Parkway STE 110,"Fayetteville,",GA,30214,No Seal,Independent Craft Brewer
5,Amici Madison,Brewpub,(706) 342-0000,174 W Washington St,"Madison,",GA,30650,No Seal,Independent Craft Brewer
...,...,...,...,...,...,...,...,...,...
168,Variant Brewing Company,Taproom,(770) 598-5002,66 Norcross St,"Roswell,",GA,30075-3866,Beer Association Member,Independent Craft Brewer
169,Whistle Top Brew Company,Taproom,(706) 776-9556,248 N Main St,"Cornelia,",GA,30531,No Seal,Independent Craft Brewer
170,Wild Heaven - West End Brewery & Gardens,Brewpub,(404) 997-8589,1010 White St SW,"Atlanta,",GA,30310,Beer Association Member,Independent Craft Brewer
171,Wild Heaven Beer,Micro,(404) 997-8589,135B Maple St,"Decatur,",GA,30030-3953,Beer Association Member,Independent Craft Brewer
172,Wild Leap Brewing Company,Micro,(706) 298-6400,308 Main St,"Lagrange,",GA,30240-4504,Beer Association Member,Independent Craft Brewer

In [6]:
addresses = df2['street_address'] + " " + df2['city'] + " " + df2['state']
address = addresses.tolist()
address

['3111 Main Street Duluth,  GA',
 '110 Werz Industrial Blvd Ste 130 Newnan,  GA',
 '150 Crane Dr Athens,  GA',
 '355 Trilith Parkway STE 110 Fayetteville,  GA',
 '174 W Washington St Madison,  GA',
 '110 Technology Parkway Peachtree Corners,  GA',
 '341 E Main St Blue Ridge,  GA',
 '100 Busch Dr NE Cartersville,  GA',
 '3361 Dogwood Dr Hapeville,  GA',
 '108 Park Ave Athens,  GA',
 '2323 Defoor Hills Rd NW Atlanta,  GA',
 '240 Lee St. Fayetteville,  GA',
 '3472 Bethany Church Rd Lincolnton,  GA',
 '1226 Ocean Blvd #1  St. Simons Island,  GA',
 '700 Lincoln St. LaGrange,  GA',
 '1036 White St SW Atlanta,  GA',
 '537 Edgewood Ave Atlanta,  GA',
 '4098 Lawrenceville Hwy Lilburn,  GA',
 '2316 Main St STE K Tucker,  GA',
 '907 Dilworth St Saint Marys,  GA',
 '9859 Davis St Braselton,  GA',
 '76 seven hills BLVD Dallas,  GA',
 '2260 Moon Station Ct NW Ste 210 Kennesaw,  GA',
 '1660 Dekalb Ave Atlanta,  GA',
 '1041 Broadway Columbus,  GA',
 '26 River Ter Ellijay,  GA',
 '1301 6th Ave, Ste C Columbus,  GA',
 '207-B West Cuyler St Dalton,  GA',
 '5810 Bond St  Cumming,  GA',
 '6640 Town Sq, Ste 510 Alpharetta,  GA',
 '79 Ross Rd Savannah,  GA',
 '27 Word Street Fairburn,  GA',
 '5504 PEACHTREE RD CHAMBLEE,  GA',
 '271 W Hancock Ave Athens,  GA',
 '355 Oneta St Bldg A100 Athens,  GA',
 '650 Langford Dr. Norcross,  GA',
 '25 S Main St Alpharetta,  GA',
 '93 W Savannah St Clayton,  GA',
 '822 Longwood Dr Richmond Hill,  GA',
 '1169 De Leon Ct Clarkston,  GA',
 '1295 Chattahoochee Ave NW Atlanta,  GA',
 '4 S. Tennessee St Cartersville,  GA',
 '1500 Lockhart Drive kennesaw,  GA',
 '106 Savannah Ave Ste B Statesboro,  GA',
 '1039 Grant Street SE Atlanta,  GA',
 '2255 Cumberland Pkwy SE Atlanta,  GA',
 '1015 Grant St SE Atlanta,  GA',
 '567 Plum Street Macon,  GA',
 '3758 E First St Blue Ridge,  GA',
 '975 Chattahoochee Ave NW Atlanta,  GA',
 '3949 North Indian Cir Kennesaw,  GA',
 '45 N Kimbell St Forsyth,  GA',
 '1570 Holcomb Bridge Rd Roswell,  GA',
 '43 Magnolia St Roswell,  GA',
 '109 S Briggs St Valdosta,  GA',
 '65 Atlanta St Marietta,  GA',
 '3085 Main St Ste 520 Duluth,  GA',
 '192 E Main St Canton,  GA',
 '1315 E Main St Blue Ridge,  GA',
 '60 Georgia Ave Atlanta,  GA',
 '616 S Main St Hiawassee,  GA',
 '2316 Main St Tucker,  GA',
 '1308 Glenwood Ave Atlanta,  GA',
 '407 Main Street Villa Rica,  GA',
 '535 East 39th Street Savannah,  GA',
 '3404 Pierce Dr NE Chamblee,  GA',
 '2765 South Main Street Kennesaw,  GA',
 '5019 West Broad Street M145 Sugar Hill,  GA',
 '308 West Ponce De Leon Decatur,  GA',
 '3535 Peachtree Rd NE Atlanta,  GA',
 '1224 Hammond Dr Atlanta,  GA',
 '2129 Northwest Pkwy SE Ste 105 Marietta,  GA',
 '457 N Chestnut Lawrenceville,  GA',
 '2855 Marconi Dr Ste 350 Alpharetta,  GA',
 '251 Market Street Alpharetta,  GA',
 '15 Atlanta Street Marietta,  GA',
 '6025 Peachtree Parkway, Suite 1 Peachtree Corners,  GA',
 '284 Prospect Place Atlanta,  GA',
 '2100 Atlanta Highway Gainesville,  GA',
 '150 Huddleston Rd Peachtree City,  GA',
 '120 Olive St Avondale Estates,  GA',
 '458 2nd St Macon,  GA',
 '3080 Jonquil Dr SE Smyrna,  GA',
 '320 Peachtree St NE Atlanta,  GA',
 '405 Cordele Rd Albany,  GA',
 '670 Trabert Ave NW Atlanta,  GA',
 '933 Lee St SW Atlanta,  GA',
 '3425 Martin Farm Rd. Suwanee,  GA',
 '21 W Bay St Savannah,  GA',
 '550 Somerset Ter NE Unit 101 Atlanta,  GA',
 '120 Whitaker St Savannah,  GA',
 '6150 Georgia Highway 400 Cumming,  GA',
 '149 Oneta St Athens,  GA',
 '484 2nd St Macon,  GA',
 '202 N West St Greensboro,  GA',
 '265 Brew St Omaha,  GA',
 '1440 Dutch Valley Pl NE Ste 2001 Atlanta,  GA',
 '5368 East Mountain Street Stone Mountain,  GA',
 '500 10th St NE Atlanta,  GA',
 '57 North Main Street Jasper,  GA',
 '56-A Fieldstone Village Dr Rock Spring,  GA',
 '450-B Third Street Macon,  GA',
 '8601 Dunwoody Pl Sandy Springs,  GA',
 '5486 Chamblee Dunwoody Rd #14 Atlanta,  GA',
 '6370 Powers Ferry Rd NW Sandy Springs,  GA',
 '120 Pine Ave Albany,  GA',
 '940 Columbia Dr Carrollton,  GA',
 '1998 Delk Industrial Blvd SE Marietta,  GA',
 '1998 Delk Industrial Blvd SE Marietta,  GA',
 '4637 South Main Street Acworth,  GA',
 '141 Railroad St Canton,  GA',
 '6255 Riverview Rd Smyrna,  GA',
 '105 Elm St Woodstock,  GA',
 '1678 Barfield Run NW Atlanta,  GA',
 '1150 5th St Bldg 61 Augusta,  GA',
 '345 Gilmer Ferry Rd Ball Ground,  GA',
 '1279 Seaboard Industrial Blvd NW Atlanta,  GA',
 '530 Flat Shoals Ave SW Atlanta,  GA',
 '813 5th St Augusta,  GA',
 '630 East Lake Drive Decatur,  GA',
 '840 Franklin Ct  Marietta,  GA',
 '1738 Macarthur Blvd NW Atlanta,  GA',
 '1311 Logan Cir NW Atlanta,  GA',
 '22 Main St Senoia,  GA',
 '574 Indian St Savannah,  GA',
 '1325 Newcastle Brunswick,  GA',
 '407 N Clayton St Lawrenceville,  GA',
 '20 Skin Alley Norcross,  GA',
 '107 E Lathrop Ave Savannah,  GA',
 '231 Collins Industrial Blvd Athens,  GA',
 '123 N Lumpkin St Monroe,  GA',
 '350 E Howell St Hartwell,  GA',
 '114 E Broughton Street Bainbridge,  GA',
 '60 Butler Street Midway,  GA',
 '300 Marietta St NW Atlanta,  GA',
 '1611 Ellsworth Industrial Blvd NW Atlanta,  GA',
 '343 US-23 Suwanee,  GA',
 '26 Old Allen Rd Commerce,  GA',
 '195 Ottley Dr NE Atlanta,  GA',
 '4500 SR-136 Talking Rock,  GA',
 '1939 Helen Hwy Cleveland,  GA',
 '755 Battery Ave SE Atlanta,  GA',
 '265 Newton Bridge Rd Athens,  GA',
 '1737 Ellsworth Industrial Blvd., NW Atlanta,  GA',
 '3003 Morrison Moore Pkwy E Dahlonega,  GA',
 '2866 Washington St AVONDALE ESTATES,  GA',
 '6655 James B Rivers Dr Stone Mountain,  GA',
 '215 Ottley Dr Atlanta,  GA',
 '292 Moreland Ave NE Atlanta,  GA',
 '121 New St Decatur,  GA',
 '777 Memorial Dr SE Atlanta,  GA',
 '249 Ponce de Leon Ave NE Atlanta,  GA',
 '944 Germany Rd Gay,  GA',
 '2003 S Bibb Dr Tucker,  GA',
 '211 E Trinity Pl Decatur,  GA',
 '12 West 41st St Savannah,  GA',
 '66 Norcross St Roswell,  GA',
 '248 N Main St Cornelia,  GA',
 '1010 White St SW Atlanta,  GA',
 '135B Maple St Decatur,  GA',
 '308 Main St Lagrange,  GA']

In [ ]:
API_KEY = 'AIzaSyB9Y5b2UyHiMSj0e3U8jJiWNZJxE5u5ndQ'
base_url = 'https://maps.googleapis.com/maps/api/geocode/json?'
lat = []
lng = []
confirmed = []
for x in address:
    query = base_url + x
    params = {
    'key': API_KEY,
    'address': x
    } 
    
    
    response = requests.get(base_url, params=params).json()
    
    geometry = response['results'][0]['geometry']
    lat.append(geometry['location']['lat'])
    lng.append(geometry['location']['lng'])
    confirmed.append(x)
    print(f"{x} found! Appending stats")

3111 Main Street Duluth,  GA found! Appending stats
110 Werz Industrial Blvd Ste 130 Newnan,  GA found! Appending stats
150 Crane Dr Athens,  GA found! Appending stats
355 Trilith Parkway STE 110 Fayetteville,  GA found! Appending stats
174 W Washington St Madison,  GA found! Appending stats
110 Technology Parkway Peachtree Corners,  GA found! Appending stats
341 E Main St Blue Ridge,  GA found! Appending stats
100 Busch Dr NE Cartersville,  GA found! Appending stats
3361 Dogwood Dr Hapeville,  GA found! Appending stats
108 Park Ave Athens,  GA found! Appending stats
2323 Defoor Hills Rd NW Atlanta,  GA found! Appending stats
240 Lee St. Fayetteville,  GA found! Appending stats
3472 Bethany Church Rd Lincolnton,  GA found! Appending stats
1226 Ocean Blvd #1  St. Simons Island,  GA found! Appending stats
700 Lincoln St. LaGrange,  GA found! Appending stats
1036 White St SW Atlanta,  GA found! Appending stats
537 Edgewood Ave Atlanta,  GA found! Appending stats
4098 Lawrenceville Hwy Lilburn,  GA found! Appending stats
2316 Main St STE K Tucker,  GA found! Appending stats
907 Dilworth St Saint Marys,  GA found! Appending stats
9859 Davis St Braselton,  GA found! Appending stats
76 seven hills BLVD Dallas,  GA found! Appending stats
2260 Moon Station Ct NW Ste 210 Kennesaw,  GA found! Appending stats
1660 Dekalb Ave Atlanta,  GA found! Appending stats
1041 Broadway Columbus,  GA found! Appending stats
26 River Ter Ellijay,  GA found! Appending stats

In [33]:
print(len(lat))
print(len(lng))
print(len(confirmed))

161
161
161

In [34]:
newDF = pd.DataFrame({
    'address': confirmed,
    'latitude': lat,
    'longitude': lng
})
newDF

                                           address   latitude  longitude
0                     3111 Main Street Duluth,  GA  34.002944 -84.145058
1     110 Werz Industrial Blvd Ste 130 Newnan,  GA  33.400220 -84.763793
2                         150 Crane Dr Athens,  GA  33.942272 -83.470440
3    355 Trilith Parkway STE 110 Fayetteville,  GA  33.469082 -84.507183
4                 174 W Washington St Madison,  GA  33.596182 -83.469315
..                                             ...        ...        ...
156                    66 Norcross St Roswell,  GA  34.025787 -84.359093
157                    248 N Main St Cornelia,  GA  34.513363 -83.527738
158                  1010 White St SW Atlanta,  GA  33.730182 -84.419203
159                     135B Maple St Decatur,  GA  33.776472 -84.276167
160                      308 Main St Lagrange,  GA  33.034826 -85.031385

[161 rows x 3 columns]

In [37]:
df2.to_csv('beer_association_scrape_clean.csv', index=False)
newDF.to_csv('beer_association_lat_lng.csv', index=False)